# Generated by Django 5.2.3 on 2025-06-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Setor')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('responsavel', models.CharField(blank=True, max_length=50, verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='TipoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Tipo de Manutenção')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Máquina')),
                ('numero_patrimonio', models.CharField(max_length=30, unique=True, verbose_name='Nº Patrimônio')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('manutencao', 'Parada para Manutenção'), ('fora', 'Fora de Uso')], default='ativa', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='maquinas/', verbose_name='Foto da Máquina')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas', to='maquinas.fabricante')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas', to='maquinas.fornecedor')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='maquinas.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('responsavel', models.CharField(max_length=50, verbose_name='Responsável')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=10, verbose_name='Status')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='maquinas.maquina')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinas.tipomanutencao')),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Peça')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinas.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='PecaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_utilizadas', to='maquinas.manutencao')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquinas.peca')),
            ],
        ),
    ]
